AppBundle\Entity\Team:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TeamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    indexes:
        name:
            columns: [ name ]
        position:
            columns: [ position ]

    fields:
        name:
            type: string
            length: 255
        position:
            type: integer
            default: 0

    oneToMany:
        users:
            orderBy: { 'name': 'ASC' }
            targetEntity: User
            mappedBy: team
            cascade: [ ]

    lifecycleCallbacks: {  }
