AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    indexes:
        name:
            columns: [ name ]
        user:
            columns: [ user ]

    fields:
        name:
            type: string
            length: 255
        user:
            type: string
            length: 255
            unique: true
        presence:
            type: integer

    oneToMany:
        periods:
            targetEntity: Period
            mappedBy: user
            cascade: [ "all" ]

    lifecycleCallbacks: {  }
