AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    indexes:
        name:
            columns: [ name ]
        user:
            columns: [ user ]
        location:
            columns: [ location ]
        birthday:
            columns: [ birthday ]

    fields:
        name:
            type: string
            length: 255
        user:
            type: string
            length: 255
            unique: true
        presence:
            type: integer
        location:
            type: string
            length: 2
        birthday:
            type: date
            nullable: true

    oneToMany:
        periods:
            orderBy: { 'id': 'DESC' }
            targetEntity: Period
            mappedBy: user
            cascade: [ ALL ]

    manyToOne:
        team:
            targetEntity: Team
            inversedBy: users
            joinColumn:
              name: team_id
              referencedColumnName: id
            onDelete: SET NULL

    lifecycleCallbacks: {  }
